const railroute = {
  id: 'sydneytrains:t2-central-granville-leppington',
  name: 'Sydney Trains - T2 !MISSING FONTS!',
  description: 'Central to Leppington via Granville',
  headsign: ['Leppington', 'Via Granville'],
  line: {
    name: 'Sydney Trains - T2',
    short: 'T2',
    colour: '#0098CD',
    textcolour: '#FFFFFF'
  },
  stations: [
    'Central',
    'Museum',
    'St James',
    'Circular Quay',
    'Wynyard',
    'Town Hall',
    'Central',
    'Redfern',
    'Macdonaldtown',
    'Newtown',
    'Stanmore',
    'Petersham',
    'Lewisham',
    'Summer Hill',
    'Ashfield',
    'Croydon',
    'Burwood',
    'Strathfield',
    'Homebush',
    'Flemington',
    'Lidcombe',
    'Auburn',
    'Clyde',
    'Granville',
    'Merrylands',
    'Guildford',
    'Yennora',
    'Fairfield',
    'Canley Vale',
    'Cabramatta',
    'Warwick Farm',
    'Liverpool',
    'Casula',
    'Glenfield',
    'Edmondson Park',
    'Leppington'
  ]
}

export default railroute
